name: MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - run: pip install mkdocs mkdocs-material
      - run: make build-docs && mkdocs gh-deploy --force
